### ISSUE TITLE
Can we measure execution path coverage?

### ISSUE THREAD

**Issue by Chobbes** [Quick700/Quick700#13]
Is there a tool to measure coverage in an executing program, kind of like AFL does, but without the actual fuzzing?

This might be a nice way to measure the performance of FuzzChick vs. QuickChick if we can get the same coverage statistics for both.

**Comment by liyishuai** [comment]
> For instance if I change the message here:
> 
> https://github.com/QuickChick/QuickChick/blob/8.8/src/quickChick.ml4#L212
> 
> QuickCheck doesn't display my modified message. Is this because `quickChick.ml4` is a Coq plugin, and my modified version isn't getting loaded even after a `make install`? Do you know how to load this?

I cannot replicate this issue. Are you using the latest version on 8.8 branch?

**Comment by Chobbes** [comment]
Yes, and I'm testing with QuickChick in proofgeneral in Tutorials.v after restarting the proof shell.

**Comment by liyishuai** [comment]
I'd suggest you try `make install V=` to see if the installation path was correct.

**Comment by Chobbes** [comment]
```
make -f Makefile.coq 
make[1]: Entering directory '/home/calvin/git/QuickChick'
make[2]: Nothing to be done for 'real-all'.
make[1]: Leaving directory '/home/calvin/git/QuickChick'
coqc -R src QuickChick -I src QuickChickInterface.v
coqc -R src QuickChick -I src DocumentationCheck.v
make -f Makefile.coq install > /tmp/tmp.pQycWpCJZM
cp quickChickTool/quickChickTool.byte /home/calvin/.opam/4.04.0+afl/bin/quickChick
```
This seems right to me, I think.

**Comment by liyishuai** [comment]
Is your Proof General using the same switch `4.04.0+afl`?

**Comment by Chobbes** [comment]
I think so, but I'm not really sure how to check... Trying to figure that out now.

**Comment by Chobbes** [comment]
AH! It's not. Now I just need to figure out how to change it...

**Comment by Chobbes** [comment]
Got it! https://opam.ocaml.org/doc/Tricks.html#Update-opam-environment-within-emacs

Thanks! Progress!

**Comment by Chobbes** [comment]
Hey, it sort of works :)!

![2018-11-26-201205_442x205_scrot](https://user-images.githubusercontent.com/5215874/49051888-aedf9e80-f1b7-11e8-8e93-fc36aab55dff.png)
![2018-11-26-201105_1084x570_scrot](https://user-images.githubusercontent.com/5215874/49051891-b1da8f00-f1b7-11e8-84f9-22317c8e1c4d.png)

**Comment by Chobbes** [comment]
Also, I believe I found an issue in bisect_ppx which makes it kind of a pain to get it to work with QuickChick:

https://github.com/aantron/bisect_ppx/issues/180

**Comment by Chobbes** [comment]
Cool, thanks to that fix I'm able to get QuickChick to automatically generate coverage reports!

![2018-11-27-093423_555x455_scrot](https://user-images.githubusercontent.com/5215874/49089061-affce400-f228-11e8-94cb-ce2d065bc290.png)

It's not ideal right now for a couple of reasons.

- QuickChick generates a different file for each test. Don't get coverage aggregated in one place.
- Each file is... Not nicely named. Hard to tell which test it corresponds to.
- Not directly related to the Coq code, because it's the extracted ocaml code.

Still, could be useful for comparing QuickChick and FuzzChick.

The changes live here:

https://github.com/QuickChick/QuickChick/tree/coverage

**Comment by Chobbes** [comment]
I instrumented FuzzChick as well. Here's a (quick) run with ifc-basic:

QuickChick:

![2018-11-28-225911_695x27_scrot](https://user-images.githubusercontent.com/5215874/49198490-50eeba80-f361-11e8-9e3f-adaadeec1c24.png)

FuzzChick:

![2018-11-28-225901_682x38_scrot](https://user-images.githubusercontent.com/5215874/49198507-682da800-f361-11e8-9a82-df99c36d2a27.png)

I only ran FuzzChick for maybe 30 seconds, so I'll try running it for a long time tomorrow. It's interesting that it's not a drop in replacement at all... We should think about why it seems to do worse!

Also I can push the coverage reporting code to the FuzzChick700 branch if you want, but it also spits out a bunch of bisect*out files in the directory that QuickChick is run for. Your call on if you want to run this.

**Questions**:
  - Why might FuzzChick measure worse coverage
  - Should I merge the coverage code into the FuzzChick700 branch? Might be annoying, might be useful?
  - Does FuzzChick ever... Terminate? Do you know if the FuzzChick command just runs forever, @liyishuai?

**Comment by Chobbes** [comment]
I did a few more experiments. Results are in the slides. Ultimately my conclusion on this small batch of tests is that FuzzChick did not lead to better coverage results. This could be for a few reasons. My suspicion is that AFL doesn't  work as well with Ocaml as it does for C programs for a variety of reasons.

It could also be that the tests that I was doing happen to not be better with AFL.

Cheers.
