### ISSUE TITLE
Slides For Friday

### ISSUE THREAD

**Issue by Chobbes** [Quick700/Quick700#14]
Are people okay with beamer, or would you prefer to use something else like PowerPoint?

I don't know how to create a powerpoint, but if somebody can send me an invite link to one I'm happy to start adding slides, and more than happy to start beamer slides.

@liyishuai @moqingyan, thoughts?

**Comment by moqingyan** [comment]
The beamer thing looks pretty cool, though I am more familiar with google slides, I don’t mind take it a try.

**Comment by Chobbes** [comment]
Oh, I forgot that google slides was an option. We could do that too.

**Comment by Chobbes** [comment]
Alright. Nobody screamed. I'm adding a beamer presentation to the git because logging into a specific google account is a pain.

https://github.com/Quick700/Quick700/tree/master/presentation

Feel free to change up the look or whatever. I just like orange.

Also, remember, if you add a code example you need `\begin{frame}[fragile]`, at least with `lstlisting`, otherwise it does weird things. If you are confused ask for help!

**Comment by Chobbes** [comment]
I've added a bunch of slides. Feel free to add more, but we should coordinate somewhat on how much time it's going to take.

I will not be available after today.

**Comment by liyishuai** [comment]
I've added performance results to the slides. My next step is to mention results on DeepWeb.

**Comment by Chobbes** [comment]
@liyishuai okay. I think you should probably mention some concrete numbers if possible.

**Comment by liyishuai** [comment]
Leo told me that the timing of experiments were not accurate. I’ll try to describe the quantitative results as much as possible.

**Comment by Chobbes** [comment]
If the timings for those experiments were not accurate then should we even report on them? That doesn't sound very good, especially if we didn't even run those experiments.

**Comment by liyishuai** [comment]
I can rerun the experiments on my side, and report if the results agree on order of magnitude.

**Comment by moqingyan** [comment]
@Chobbes I tried to time it once and it takes 12 minutes. I think I can practice it down to 10 minutes and probably get rid of some slides as well.

**Comment by Chobbes** [comment]
We're probably right on target then, that's great!
