### ISSUE TITLE
Not sure how to use Ocaml with apache

### ISSUE THREAD

**Issue by moqingyan** [Quick700/Quick700#15]
I tried to use mod_caml library to enable Ocaml with apache, but the library is quite out of date. Support to apache 1.3 and failed to compile. Any suggestions :( ? The Apache Server is the original Apache Server instrumented by afl.

**Comment by Chobbes** [comment]
I don't think we need mod_caml. This is for using ocaml as CGI scripts for Apache. I.e., people make a request to a web page and it runs some ocaml code. But that's not what we're doing, we just want to launch apache from ocaml in such a way that AFL can see it.

What I've been saying is we can potentially just use `Sys.command` to launch apache, just as you would from a shell script. I think AFL might be able to work with any instrumented binary that you launch.

https://caml.inria.fr/pub/docs/manual-ocaml/libref/Sys.html

Maybe there's an issue where `Sys.command` runs apache in a shell that's not instrumented --- if that matters then we should just try `Unix.fork` followed by `Unix.execvpe` or `Unix.execvp`.

https://caml.inria.fr/pub/docs/manual-ocaml/libref/Unix.html

**Comment by Chobbes** [comment]
@liyishuai actually, DeepWeb tests use quickChickTool. I don't know much about what quickChickTool does --- does it use quickChick.mlg too?

**Comment by liyishuai** [comment]
DeepWeb test on [fuzz](/DeepSpec/DeepWeb/tree/fuzz) branch should be triggered with `make apache` or whatever server, followed by `make`.

**Comment by Chobbes** [comment]
@liyishuai I'm not sure what point you're trying to make? Could you elaborate?

My question is: **does quickChickTool end up running tests using the quickChick.mlg file just like normal QuickChick tests inline in Coq?**

I think quickChickTool just goes through and extracts sections / swaps mutants in, and then runs the created Coq file normally. Is this correct?

**Comment by liyishuai** [comment]
Yes, but it doesn't work with `FuzzChick` command yet.
I'll be back after 11:00.

**Comment by Chobbes** [comment]
https://github.com/Chobbes/QuickChick/commit/2caf722e21b2560d51ed3c4c66960ee8294185af

This is my first attempt at running "apache" (in this case just the program 'yes' for testing) from ocaml.

QuickChick does launch the external process, but `QuickChick` commands in Coq never return --- I think ocaml is waiting for the child process to die? Might have to explicitly kill the child process when done testing.
