### ISSUE TITLE
Do you know when the  ./configure file is generated? 

### ISSUE THREAD

**Issue by thinkycx** [Quick700/Quick700#17]
When I get clone the httpd and going to compile it,  I get the error : cannot find the ./configure.
![image](https://user-images.githubusercontent.com/13138128/50392107-3d7b1780-0786-11e9-8673-dd261a75fa08.png)

I have read your dockerfile , I think we are the same. But when use your docker, the file is generated. Do you know when the  ./configure file is generated? It's not in the apache's httpd source.

**Comment by liyishuai** [comment]
It's not included in the repo. Only the tarball releases contain the generated `configure`.

**Comment by liyishuai** [comment]
As your screenshot shows, `buildconf` complains that `autoheader` and `autoconf` are not installed.

**Comment by thinkycx** [comment]
> As your screenshot shows, `buildconf` complains that `autoheader` and `autoconf` are not installed.

You are right. I compare the output of my log and you docker log, I should install  autoconf. Thank you.

By the way, the result of hongfuzz seems not well. Do you have any crash now?
![image](https://user-images.githubusercontent.com/13138128/50392242-a7e08780-0787-11e9-92c2-bcbf4a07a37e.png)

**Comment by liyishuai** [comment]
We haven't found a way to have it running non-trivially yet.

**Comment by thinkycx** [comment]
> We haven't found a way to have it running non-trivially yet.

What does  **non-trivially**  mean？

Besides, I found that after httpd is built  it seems that it cannot run  normally.
It cannot serve and quit immediately.
output: 
![image](https://user-images.githubusercontent.com/13138128/50392478-bc258400-0789-11e9-9217-48e62a8f3431.png)

I have test your binary in docker, it is same with me.

**Comment by liyishuai** [comment]
By non-trivially I meant processing a request and sending the response somewhere we can see. Notice that the server under test is patched and should behave somehow differently from out-of-box Apache.

**Comment by thinkycx** [comment]
> By non-trivially I meant processing a request and sending the response somewhere we can see. Notice that the server under test is patched and should behave somehow differently from out-of-box Apache.

I notice that the httpd process start and exit quickly. 
![image](https://user-images.githubusercontent.com/13138128/50392735-c6e11880-078b-11e9-9881-484b13047741.png)

As I didn't use such as tcpdump to see the network data, I guess what cause the result is that the apache httpd cannot run as normal. Wish you find the reason.

Beside, do you want to fuzz other web servers such as nginx? Maybe it is a good change to study nginx and hunt cves in it.

**Comment by liyishuai** [comment]
I'd suggest running the server manually and analyse at code level. If the patched server is to process one request and exit, such "exit quickly" behaviour is actually expected.
We're happy to fuzz other commodity web servers for research purposes, provided the engineering effort is worth it.

**Comment by thinkycx** [comment]
OK. I think that ` analyse at code level` is difficult and I don't know how to do it at present.

By the way, I use tcpdump to capture the lo and eth0 interface by `tcpdump -i lo -s 1500 -v -w /root/123.pcap`.Then, I start honggfuzz to fuzz and there is no data transfered . So I think the httpd exit with code 1 is not to out expected.

However, while there is a will, there is a way. Wish you can analyse the reason and solve it .

**Comment by liyishuai** [comment]
I'm afraid I have to give this project a low priority, until it's on the critical path of my research.

**Comment by thinkycx** [comment]
> I'm afraid I have to give this project a low priority, until it's on the critical path of my research.

The same. :)

**Comment by thinkycx** [comment]
I have read the author's blog and change the fuzzing bash script:
```
honggfuzz  -Q  -f corpus_http1/ -w ./httpd.wordlist -- /root/Hackit/apache/dist/bin/httpd -X -f /root/Hackit/apache/dist/conf/httpd.conf.h1
```
You can use it and check the output log.
Now my output seems a little better than before but still have some errors such as `AH00016: Configuration Failed`.
![image](https://user-images.githubusercontent.com/13138128/50410733-d026bf80-0835-11e9-8952-660aef1bd746.png)

**Comment by robertswiecki** [comment]
Hi,

Author of honggfuzz here, I was redirected to this project througgh some issue entry in google/honggfuzz.

So, your apache is exiting early, due to some problem with configuration, I'd suggest removeing everything related to proxying there, e.g


```
ProxyStatus On
ProxyVia On
<Location "/proxy/">
    ProxyPass "http://127.0.0.1:8080/index.html"
    SetEnv force-proxy-request-1.0 1
    SetEnv proxy-nokeepalive 1
</Location>
```

Maybe it'll help. BTW, you shouldn't be seeing "EXITED, exit code: 1" during normal operation, it means that httpd is probably not even processing your requests.

As for crashes, I just tried it with newest httpd from git, and it crashed for me with the httpd.conf.h2

```
$ ~/src/honggfuzz/honggfuzz -P -f IN/ -- ./httpd/httpd -DFOREGROUND -f /home/jagger/fuzz/apache/dist/conf/httpd.conf.h2
------------------------[  0 days 00 hrs 00 mins 02 secs ]----------------------
  Iterations : 2,767 [2.77k]
  Mode [1/2] : Feedback Driven Dry Run
      Target : ./httpd/httpd -DFOREGROUND -f /h.....che/dist/conf/httpd.conf.h2
     Threads : 8, CPUs: 16, CPU%: 660% [41%/CPU]
       Speed : 915/sec [avg: 1,383]
     Crashes : 3 [unique: 2, blacklist: 0, verified: 0]
    Timeouts : 0 [10 sec]
 Corpus Size : 907, max: 1,048,792 bytes, init: 7,129 files
  Cov Update : 0 days 00 hrs 00 mins 00 secs ago
    Coverage : edge: 16,651 pc: 404 cmp: 186,494
---------------------------------- [ LOGS ] ------------------/ honggfuzz 1.7 /-
Size:1024 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/0, Tot:0/0/0/16534/403/185248
Size:128 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/0, Tot:0/0/0/16535/403/185248
Size:17865 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/0, Tot:0/0/0/16536/403/185248
Size:1024 (i,b,hw,edge,ip,cmp): 0/0/0/2/0/34, Tot:0/0/0/16538/403/185282
Size:24353 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/1, Tot:0/0/0/16538/403/185283
Size:32000 (i,b,hw,edge,ip,cmp): 0/0/0/33/0/491, Tot:0/0/0/16571/403/185774
Size:238 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/3, Tot:0/0/0/16571/403/185777
Size:8631 (i,b,hw,edge,ip,cmp): 0/0/0/2/0/1, Tot:0/0/0/16573/403/185778
Size:1024 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/1, Tot:0/0/0/16574/403/185779
Size:1024 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/1, Tot:0/0/0/16575/403/185780
Size:53 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/0, Tot:0/0/0/16576/403/185780
Size:127 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/2, Tot:0/0/0/16576/403/185782
Crash: saved as './SIGSEGV.PC.ade00e.STACK.f022cd7e1.CODE.1.ADDR.0x70.INSTR.mov____(%r14),%rbx.fuzz'
Size:229 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/0, Tot:0/0/0/16577/403/185782
Size:429 (i,b,hw,edge,ip,cmp): 0/0/0/8/1/90, Tot:0/0/0/16585/404/185872
Size:304 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/1, Tot:0/0/0/16586/404/185873
Size:59 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/0, Tot:0/0/0/16587/404/185873
Size:578960 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/4, Tot:0/0/0/16587/404/185877
Size:57 (i,b,hw,edge,ip,cmp): 0/0/0/2/0/1, Tot:0/0/0/16589/404/185878
Size:287 (i,b,hw,edge,ip,cmp): 0/0/0/2/0/3, Tot:0/0/0/16591/404/185881
Size:64246 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/0, Tot:0/0/0/16592/404/185881
Size:128 (i,b,hw,edge,ip,cmp): 0/0/0/2/0/31, Tot:0/0/0/16594/404/185912
Size:1024 (i,b,hw,edge,ip,cmp): 0/0/0/2/0/1, Tot:0/0/0/16596/404/185913
Size:393508 (i,b,hw,edge,ip,cmp): 0/0/0/52/0/565, Tot:0/0/0/16648/404/186478
Crash (dup): './SIGSEGV.PC.ade00e.STACK.f022cd7e1.CODE.1.ADDR.0x70.INSTR.mov____(%r14),%rbx.fuzz' already exists, skipping
Size:461 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/3, Tot:0/0/0/16649/404/186481
Crash: saved as './SIGSEGV.PC.ade00e.STACK.f022cd7e1.CODE.0.ADDR.(nil).INSTR.mov____(%r14),%rbx.fuzz'
Size:429 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/2, Tot:0/0/0/16649/404/186483
Size:779 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/4, Tot:0/0/0/16650/404/186487
Size:8662 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/6, Tot:0/0/0/16650/404/186493
Size:30852 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/1, Tot:0/0/0/16650/404/186494
Size:20 (i,b,hw,edge,ip,cmp): 0/0/0/1/0/0, Tot:0/0/0/16651/404/186494
Size:59839 (i,b,hw,edge,ip,cmp): 0/0/0/0/0/1, Tot:0/0/0/16651/404/186495
^CSignal 2 (Interrupt) received, terminating
Terminating thread no. #1, left: 8
Terminating thread no. #5, left: 7
Terminating thread no. #2, left: 6
Terminating thread no. #3, left: 5
Terminating thread no. #7, left: 4
Terminating thread no. #4, left: 3
Terminating thread no. #6, left: 2
Terminating thread no. #0, left: 1
All threads done
Summary iterations:2810 time:3 speed:936
```
