### ISSUE TITLE
Get Honggfuzz Running

### ISSUE THREAD

**Issue by Chobbes** [Quick700/Quick700#2]
Calvin has honggfuzz running.

**Comment by liyishuai** [comment]
Not running on my side:
```shell
honggfuzz/honggfuzz -f hong-apache/corpus_http1 -w hong-apache/httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f $PWD/httpd.conf.h1
```
> [2018-10-31T13:34:59-0400][E][92305] cmdlineVerify():169 You must specify '___FILE___' if the -s (stdin fuzzing) or --persistent options are not set
[2018-10-31T13:34:59-0400][F][92305] main():183 Parsing of the cmd-line arguments failed

Which version of Honggfuzz are you using?

**Comment by Chobbes** [comment]
We talked about this in the hallway, but for the record: I am using the honggfuzz in the submodule. I don't get this problem.

Have you tried setting --persistent for honggfuzz? i'm not really sure what it does, but that seems to be the complaint.

Also maybe try looking at the issue we opened on the honggfuzz repo. There were some tips to get more output.

**Comment by liyishuai** [comment]
Fixed by appending `___FILE___` to the command. I'll try to build a docker for this.

**Comment by liyishuai** [comment]
Our project is listed by honggfuzz! https://github.com/google/honggfuzz/commit/d52255c3134c452c6183ea82dbe87dad336ad966
