### ISSUE TITLE
Get FuzzChick Running

### ISSUE THREAD

**Issue by Chobbes** [Quick700/Quick700#5]
Depends on #4

**Comment by Chobbes** [comment]
We should probably try to get FuzzChick running this week some time. @liyishuai do you know what the state of FuzzChick is? Have you tried running it?

Even if we can't find anything interesting with Honggfuzz, I think our focus should be on FuzzChick.

I'll try after my midterm.

**Comment by liyishuai** [comment]
I was able to run [fuzz-ifc](/QuickChick/QuickChick/tree/FuzzChick/examples/fuzz-ifc).
To fuzz our web server, I have two steps in mind:
1. Simply wrap an existing DeepWeb tester with FuzzChick driver, expecting not-so-good coverage, and then
2. Try to remove the network, linking the client and server into one binary program so that the fuzzer can analyze thoroughly, expecting better coverage.

**Comment by Chobbes** [comment]
It's not immediately clear to me how to run fuzz-ifc. Can you point us in the right direction, @liyishuai? Is AFL built into QuickChick, or do you run it separately, or...?

Okay, I'm interested in 2.

I'm also curious if we can sort of hack a fuzzer to work even over the network just by making a program that takes different paths based on the output it sees, haha. Not sure that would work well in practice, though.

**Comment by liyishuai** [comment]
QuickChick compiles a binary tester (that crashes when the checker fails), and runs AFL on it via system call. @lemonidas correct me if I’m wrong.

**Comment by lemonidas** [comment]
What Yishuai said is correct. The current version in the FuzzChick branch compiles a binary tester that can be targeted by AFL. If you want to make changes, I'd recommend making a new branch, as the current version is under heavy use for the next 10 days.

**Comment by Chobbes** [comment]
@liyishuai I'm still not really sure what to do with the fuzz-ifc directory. How do you run it?

**Comment by liyishuai** [comment]
You need to `opam switch VERSION+afl`, where `VERSION` >= 4.04.0, and then `opam install afl`.

**Comment by Chobbes** [comment]
@liyishuai cool, I have that now. I can run `Tutorial.v` with the fuzzchick variant of QuickChick.

I still have no idea what to do with `fuzz-ifc`. What do you actually do with `fuzz-ifc`?

**Comment by Chobbes** [comment]
What are you doing to "run" fuzz-ifc? Like, are you just doing `./runtests.sh`, or is there something else that you have to do?

**Comment by Chobbes** [comment]
```
 $ make test
touch Driver.v && make
make[1]: Entering directory '/home/calvin/git/Quick700/fuzzchick/QuickChick/examples/fuzz-ifc'
make -f Makefile.coq
make[2]: Entering directory '/home/calvin/git/Quick700/fuzzchick/QuickChick/examples/fuzz-ifc'
COQDEP VFILES
COQC Driver.v
make[2]: Leaving directory '/home/calvin/git/Quick700/fuzzchick/QuickChick/examples/fuzz-ifc'
make[1]: Leaving directory '/home/calvin/git/Quick700/fuzzchick/QuickChick/examples/fuzz-ifc'
 $                                                                                
```

I don't think it does anything? There's no Quickchick commands in everything that it builds.

**Comment by liyishuai** [comment]
1. `opam install afl afl-persistent`
2. `mkdir output`
3. `./runtests.sh`
4. `tail -f output/fuzz_seeded_SSNI_arbitrary_*.out`

**Comment by Chobbes** [comment]
Okay, that does something!

**Comment by lemonidas** [comment]
1) You can remove the afl-persistent dependency if you modify src/quickChick.ml4 to not link against it.
It is 99% unecessary.
2) ./runtests only adds a QuickChick/FuzzChick command at the end of each file and runs it, redirecting the output.
