### ISSUE TITLE
Look into afl directory.

### ISSUE THREAD

**Issue by Chobbes** [Quick700/Quick700#8]
Calvin doesn't know what this is.

**Comment by liyishuai** [comment]
Currently it contains the Dockerfiles to run fuzzing.
The problem is zero coverage.

**Comment by Chobbes** [comment]
Zero coverage, or zero crashes?

Why would it get zero coverage... Is this apache instrumented the same way as honggfuzz? I.e., does the fuzzer actually have access to apache's trace?

Was apache compiled with AFL instrumentation?

**Comment by liyishuai** [comment]
I believe so. You could check Dockerfile that contains all the compile commands.

**Comment by Chobbes** [comment]
Okay, looks like it. Hmmm! That's annoying. I'll try running it.
