### ISSUE TITLE
Look into zero coverage issue with AFL

### ISSUE THREAD

**Issue by Chobbes** [Quick700/Quick700#9]
Currently AFL is giving zero coverage when testing the apache server, as mentioned here: https://github.com/Quick700/Quick700/issues/8

Let's look into this.

**Comment by Chobbes** [comment]
I'm going to try running the Dockerfile and see if I still get 0 coverage. It's building right now.

**Comment by liyishuai** [comment]
Add `-it` flag to `docker run`.

**Comment by Chobbes** [comment]
Got it. Still not getting any paths, hmmm.

I think we should focus on FuzzChick maybe. Having the baseline is nice, but if we can't get the tools to work, I dunno...

**Comment by liyishuai** [comment]
To start with, look into [DeepWeb](/DeepSpec/DeepWeb/tree/master/src/DeepWeb) directory. It's rather old, but somehow documented. Try to run the tests, especially [those on external servers](/DeepSpec/DeepWeb/tree/master/src/DeepWeb#test-external-servers).

**Comment by Chobbes** [comment]
I believe @moqingyan fixed this?
